swagger: '2.0'
info:
  title: NFP Breast Feeding API
  description: NFP App API for Backend Serverless Functions
  version: "1.0.0"
Parameters:
    DisableUserFunction:
        Type: String
# the domain of the service
host: execute-api.us-east-1.amazonaws.com
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /
produces:
  - application/json
paths:
  /cognito/disableuser:
    post:
      summary: disable a user
      description: |
        Disables a user in the app cognito pool when they withdraw from the study.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          description: New user details.
          schema:
            $ref: '#/definitions/cognitouser'
      tags:
        - cognito
      x-amazon-apigateway-request-validator: "Validate body"
      x-amazon-apigateway-integration:
        type: aws
        uri: !Sub 'arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:551307643672:function:${AWS::DisableUserFunction}/invocations'        #credentials: arn:aws:iam::551307643672:role/DisableUserAfterWithdrawCogntioUserPools 


        httpMethod: POST
        responses:
          "default":
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin : "'*'"
          "BAD.*":
            statusCode: "400"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin : "'*'"
          "INT.*":
            statusCode: "500"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin : "'*'"
      responses:
        200:
          description: The username of the new user and set of temporary credentials
          headers:
            Access-Control-Allow-Origin:
              type: "string"
          
        400:
          description: Bad request
          headers:
            Access-Control-Allow-Origin:
              type: "string"
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Internal error
          headers:
            Access-Control-Allow-Origin:
              type: "string"
          schema:
            $ref: '#/definitions/Error'
  
definitions:
  cognitouser:
    title: Cognito Disable User
    type: object
    maxProperties: 2
    
    properties:
      username:
        type: string
      userpool:
        type: string
    required:
      - username
      - userpool
  Error:
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
x-amazon-apigateway-request-validators:
  Validate body:
    validateRequestParameters: false
    validateRequestBody: true