AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    NFP Breastfeeding SAM 

Globals:
    Function:
        Timeout: 20
# main template
Resources:
    Api:
        Type: AWS::Serverless::Api
        Properties: 
            StageName: NFPBreastFeedingAPI
            DefinitionBody:
                swagger: '2.0'
                info: 
                    title: NFP Breast Feeding API
                    description: NFP App API for Backend Serverless Functions
                    version: "1.0.0"
                Parameters:
                    DisableUserFunction:
                        Type: String
                # the domain of the service
                host: execute-api.us-east-1.amazonaws.com
                # array of schemes
                schemes:
                - https
                # will be prefixed to all paths
                basePath: /
                produces:
                - application/json
                paths:
                    /cognito/disableuser:
                        post:
                            summary: disable a user
                            description: |
                                Disables a user in the app cognito pool when they withdraw from the study.
                            consumes:
                            - application/json
                            produces:
                            - application/json
                            parameters:
                            - in: body
                            name: body
                            description: Definition of cognito user
                            schema:
                                $ref: '#/definitions/cognitouser'
                            tags:
                                - cognito
                            x-amazon-apigateway-request-validator: "Validate body"
                            x-amazon-apigateway-integration:
                                type: aws
                                uri: !Sub 'arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:551307643672:function:${DisableUserFunction}/invocations'        #credentials: arn:aws:iam::551307643672:role/DisableUserAfterWithdrawCogntioUserPools 
                                httpMethod: POST
                                responses:
                                    "default":
                                        statusCode: "200"
                                        responseParameters:
                                            method.response.header.Access-Control-Allow-Origin : "'*'"
                                    "BAD.*":
                                        statusCode: "400"
                                        responseParameters:
                                            method.response.header.Access-Control-Allow-Origin : "'*'"
                                    "INT.*":
                                        statusCode: "500"
                                        responseParameters:
                                            method.response.header.Access-Control-Allow-Origin : "'*'"
                            responses:
                                "200":
                                    description: The result of disabling a cognito user.
                                    headers:
                                        Access-Control-Allow-Origin:
                                            type: "string"
                            
                                "400":
                                    description: Bad request
                                    headers:
                                        Access-Control-Allow-Origin:
                                            type: "string"
                                    schema:
                                        $ref: '#/definitions/Error'
                                "500":
                                    description: Internal error
                                    headers:
                                        Access-Control-Allow-Origin:
                                            type: "string"
                                    schema:
                                        $ref: '#/definitions/Error'
                
                definitions:
                    cognitouser:
                        title: Cognito Disable User
                        type: object
                        maxProperties: "2"
                        
                        properties:
                            username:
                                type: string
                            userpool:
                                type: string
                            required:
                            - username
                            - userpool
                    Error:
                        properties:
                            code:
                                type: integer
                                format: int32
                            message:
                                type: string
                            fields:
                                type: string
                x-amazon-apigateway-request-validators:
                        Validate body:
                            validateRequestParameters: false
                            validateRequestBody: true
                            
           
    DisableUserFunction:
        Type: AWS::Serverless::Function 
        Properties:
            CodeUri: target/cognito-1.0.0.jar
            Handler: nfpbreastfeedingcognitouserdisable.cognito.ProxyWithStream::handleRequest
            Runtime: java8
            Events:
                disableuser:
                    Type: Api 
                    Properties:
                        Path: /cognito/disableuser
                        Method: POST
                        RestApiId: !Ref Api
 
Outputs:

    NFPBreastFeedingApi:
        Description: "API Gateway endpoint URL for Dev stage for Disable User Function"
        Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/Dev/cognito/disableuser"

    DisableUserFunction:
      Description: "Disable User Function ARN"
      Value: !GetAtt DisableUserFunction.Arn

    DisableUserFunctionIamRole:
      Description: "Implicit IAM Role created for Disable User function"
      Value: !GetAtt DisableUserFunction.Arn
